### ISSUE TITLE
Missing stylelint@^9.0.0

### ISSUE THREAD

**Issue by ericchenkai** [MichMich/MagicMirror#1260]
I encounter a WARN today to manual install MM on raspberry Pi 3B today (April 9th, 2018). 

`npm WARN grunt-stylelint@0.10.0 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.`

It turned out stylelint@8.4.0 was installed instead of 9.0.0. 
I run `npm install stylelint@^9.0.0` and it seemed solved. 

For your reference.

**Comment by ericchenkai** [comment]
I think it is, partial, solved by now. I will close this issue.

**Comment by CountParadox** [comment]
this happened for me today, so it must not be fixed.

running `npm install stylelint@^9.0.0` did not fix it for me
