### ISSUE TITLE
Electron not starting on Raspberry Pi

### ISSUE THREAD

**Issue by MichMich** [MichMich/MagicMirror#145]
I just installed a Raspberry Pi with a clean Jessie installation to give MM2 a try.
Unfortunately, the app will not start, and doesn't give any errors of feedback.

See image below. Any ideas, @paviro & @nhubbard?

![screen shot 2016-04-06 at 16 57 26](https://cloud.githubusercontent.com/assets/210954/14321322/066d5b84-fc19-11e5-90e8-c68b425a5b6f.png)

**Comment by paviro** [comment]
Strange, maybe try `npm config set log level silly`?

**Comment by MichMich** [comment]
![screen shot 2016-04-07 at 09 36 16](https://cloud.githubusercontent.com/assets/210954/14343902/3f94a06c-fca4-11e5-816c-a8969e1f6843.png)

No real helpful information.

**Comment by MichMich** [comment]
Ive tried the [Electron Quick Start](https://github.com/electron/electron-quick-start.git), but that seems to have the same issue. I opened an issue in the Electron repository: https://github.com/electron/electron/issues/5069

**Comment by nhubbard** [comment]
That's odd. Never have I seen a Node app that crashes without a stack trace.

**Comment by MichMich** [comment]
It doesn't even seem to crash. It exits with code 0. But it's an Raspberry Issue, since the Electron Quick Start does the same.

**Comment by paviro** [comment]
Strange, that it works without any Problems  for me...

**Comment by MichMich** [comment]
@paviro Which RPi are you using? 2 or 3?  On the Electron issue they said it had something to do with the RPi type: https://github.com/electron/electron/issues/5069

**Comment by paviro** [comment]
Pi 2 with Jessie.
> Am 08.04.2016 um 11:36 schrieb Michael Teeuw <notifications@github.com>:
> 
> electron/electron#5069 <https://github.com/electron/electron/issues/5069>

**Comment by MichMich** [comment]
That's strange indeed. I'm using the same Pi. :-/

**Comment by paviro** [comment]
Yeah figured so, that's what I don't get... Does not make any sense.

**Comment by MichMich** [comment]
@pavario, so I did another reinstall. Again without succes. Besides the magic mirror installer, I did not run any other installers.

I'm running: **2016-03-18-raspbian-jessie**
Node: **v5.10.1**
GPU memory: **256MB**

Any differences between the above and your situation?

**Comment by paviro** [comment]
Seems to be the same thing I did. Well I installed `node` via `apt-get` before but removed it again.

**Comment by MichMich** [comment]
Same problem with v4.0.0. 

But how can it be that you are running v4.0.0 if you used the installer?

**Comment by paviro** [comment]
There was no installer when I installed it but I did the same things the installer does just with the older node version.

**Comment by MichMich** [comment]
If you have an empty card laying around, would you mind trying the installer on a clean jessie installation?

**Comment by paviro** [comment]
I'll see if I find one :)

**Comment by MichMich** [comment]
Fun fact! I just put the same SD-card into a Pi3. Tried `npm start` and it just worked! 
So there seems to be an issue with the Pi2.

**Comment by pvyParts** [comment]
in regards to the installer, this is how i installed node ( before i realized there was an installer )
`curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
`
`sudo apt-get install -y nodejs
`
[from here](http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/)

**Comment by MichMich** [comment]
@pvyParts: and does the MM run on a RPi2 in your case?

**Comment by pvyParts** [comment]
it did when i had one (read till few days ago) i blew mine up tho unfortunately so i'm on a 3 now.

**Comment by MichMich** [comment]
Interesting! Thanks for letting me know.

**Comment by Pukinator** [comment]
I have the same issue in a Pi B+ running Jessie

**Comment by MichMich** [comment]
I tried it yesterday on a different Pi 2, and that one worked. I've got no clue yet on the reason.

**Comment by nhubbard** [comment]
Could the Pi be bad? We might want to involve @raspberrypi to see if the issues are related.

**Comment by MichMich** [comment]
Nope, it seems like a electron issue. If you run node serveronly there is no issue.

**Comment by Bangee44** [comment]
I have the same problems with the PI 1..

**Comment by MichMich** [comment]
Ok! Issue solved! It appeared that the non working Pi 2 was actually a Pi 1 B+ (They look very similar!)

In other words: Electron does not work on Pi 1, but does work without any issues on Pi 2 & 3.

**Comment by Pukinator** [comment]
So what should I do when I own a Pi B+?

**Comment by MichMich** [comment]
You can start the app using `node server only`, this will start the app, but it will not launch a browser. You'll need to setup a browser solution yourself (like with MagicMirror v1).

**Comment by Pukinator** [comment]
Ok I'll try that

**Comment by desq42** [comment]
Hi. 

I´m having an issue starting "electron" on my Raspberry Pi 2 (Jessie);

npm ERR! Linux 4.4.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! magicmirror@2.0.0 start: `electron js/electron.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the magicmirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron js/electron.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs magicmirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls magicmirror
npm ERR! There is likely additional logging output above.

Has anybody a clue what am I doing wrong?

Thanks,

desq

**Comment by MichMich** [comment]
Could you try

    node serveronly 

To see if that works?

**Comment by jferch** [comment]
I believe I had the same error when the automatic magicmirror2 installer did not finish the setup for some reason. I installed node.js for [ARMv7](https://nodejs.org/en/download/stable/) manually which worked for me then. Not sure if that's the case for you as well, @desq42 ?!

**Comment by desq42** [comment]
node serveronly works. electron seems so have an issue with my raspberry pi 2 (it´s really a 2).
I´m going to try jferch solution later today.

**Comment by desq42** [comment]
no cigar. even did a complete reinstall. I´ll have to live with "serveronly".

**Comment by MichMich** [comment]
So you tried: clean jessie install and installer script, and that didn't work?

**Comment by crazywolf132** [comment]
Hey. As of today, I am on a RPI 2. It is defenetally a 2. I am running wheezy and everything is fine in `serveronly` ...But when i try to just run `npm start` it fails

**Comment by MichMich** [comment]
Please try Jessie

**Comment by krantni** [comment]
I had along the same issue and have a I have a Pi 2, Node v6.1.0, npm v3.8.6, full version of Jessie. I noticed at the beginning of the npm install I got:
`npm WARN prefer global colorguard@1.2.0 should be installed with -g`
`npm WARN prefer global coffee-script@1.10.0 should be installed with -g`

I then ran:
`sudo npm install -g coffee-script`
`sudo npm install -g colorguard`
And it got rid of all the warnings. Now the only way `npm start` works is by using `startx` going into the Terminal and running it from there.

**Comment by matthiasschroeder** [comment]
Same for me. I am running Jessie on a raspberry pi 3.

**Comment by masters1222** [comment]
Hi just wanted to report that I am running a pi 3 with Jesse and am having the same exact issue.

**Comment by markbarton** [comment]
Just want to add my report as well - just got a pi 3 and have the same problem Electron will not start - runs fine if I run startx and then use the command console.

**Comment by MichMich** [comment]
> runs fine if I run startx and then use the command console.

Could you elaborate on this? 

How do you start the mirror? Which command? Via SSH or Pi Terminal? Jessie or Jessie Lite? Which Node version? How did you install Magic Mirror. What do the logs say?

**Comment by markbarton** [comment]
Hi Mich - sorry a bit of a newbie to the pi but ok with NodeJS so bear with me ;-)

I installed using SSH and attempted to run Magic Mirror via SSH - using the display command.

This is what I got:

npm ERR! Linux 4.4.9-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! magicmirror@2.0.0 start: `electron js/electron.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the magicmirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron js/electron.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs magicmirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls magicmirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/npm-debug.log

I then tried npm start from the command console directly on the Pi (when it first boots) and got the same error.

If I launch the GUI using startx and the open a command prompt in there and use the npm start it works fine.

nodeserver only works fine whereever I run it.

So its only electron running from either a SSH session or the command prompt thats the problem - do you think its a security / privileges issue?

**Comment by markbarton** [comment]
Heres the npm-debug.log contents

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.0.0~prestart: magicmirror@2.0.0
6 silly lifecycle magicmirror@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle magicmirror@2.0.0~start: magicmirror@2.0.0
8 verbose lifecycle magicmirror@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle magicmirror@2.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle magicmirror@2.0.0~start: CWD: /home/pi/MagicMirror
11 silly lifecycle magicmirror@2.0.0~start: Args: [ '-c', 'electron js/electron.js' ]
12 silly lifecycle magicmirror@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle magicmirror@2.0.0~start: Failed to exec start script
14 verbose stack Error: magicmirror@2.0.0 start: `electron js/electron.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid magicmirror@2.0.0
16 verbose cwd /home/pi/MagicMirror
17 error Linux 4.4.11-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.2.1
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error magicmirror@2.0.0 start: `electron js/electron.js`
22 error Exit status 1
23 error Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the magicmirror package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron js/electron.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs magicmirror
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls magicmirror
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MichMich** [comment]
So just to be sure: when you talk about the "command prompt" on the pi, do you mean the promt it boots into? Or do you mean a terminal window on the Pi after it boots into the GUI?

**Comment by markbarton** [comment]
prompt it boots into - doesnt work
command prompt window in gui - works fine

**Comment by MichMich** [comment]
That's the expected result. Electron (In which MagicMirror runs) is a GUI application, so it needs a GUI environment. It can't start that environment for you.

**Comment by markbarton** [comment]
Ah - thanks.

Seems obvious in hindsight - thats what the Auto start instructions were for.

**Comment by sundaytill** [comment]
markbarton/michmich 
     I have the same bug ,  i noticed there is no  config directory ( MagicMirror/config/ ) from the boot terminal. I did install the config directory by ssh.  I am able to npm start from the terminal after  the startX command from the host machine and there is a MagicMirror/config directory on the host machine
How do I fix this ?  Is this an autostart problem ?  A directory issue? I'm really new at all of this please excuse my lack of experience and not understanding  these posts

**Comment by markbarton** [comment]
Hi,

It wasnt a bug - it was my lack of understanding :-)

You need to use PM2 - which is a nodejs Package Manager to provide the
autostart capability for the Magic Mirror - https://github.com/Unitech/pm2

Its pretty straight forward to use.

Mark

On 18 June 2016 at 09:45, sundaytill <notifications@github.com> wrote:

> markbarton/michmich
> I have the same bug , i noticed there is no config directory (
> MagicMirror/config/ ) from the boot terminal. I did install the config
> directory by ssh. I am able to npm start from the terminal after the startX
> command from the host machine and there is a MagicMirror/config directory
> on the host machine
> How do I fix this ? Is this an autostart problem ? A directory issue? I'm
> really new at all of this please excuse my lack of experience and not
> understanding these posts
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MichMich/MagicMirror/issues/145#issuecomment-226930003>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAFqd5LBlkFJh8leA_epCOPt4Rrq-1l6ks5qM7AYgaJpZM4IBLKc>
> .
>



-- 

http://www.markbarton.com

**Comment by MichMich** [comment]
@sundaytill This doesn't seem related to this issue. Please open a support question in http://forum.magicmirror.builders 

Thanks!

**Comment by sundaytill** [comment]
Hi
    Mark ,
Thank you

**Comment by Serubin** [comment]
Any update on the issue in the op? Seems the thread got a bit sidetracked ;)

**Comment by MichMich** [comment]
Yeah the OP is solved a while ago. Had something to do with an older Electron version. Not relevant anymore.

**Comment by blindarrow** [comment]
Still getting the issue on a Raspberry Pi 3. The auto-install script happens to mention this as well:

```
Installing dependencies ...
npm WARN deprecated electron-prebuilt@1.3.8: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global colorguard@1.2.0 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g

> electron-prebuilt@1.3.8 postinstall /home/pi/MagicMirror/node_modules/electron-prebuilt
> node install.js
```

I then ran...

```
npm install -g coffee-script
npm install -g colorguard
npm install -g jsonlint
npm install -g electron

Still getting the issue. This is on a Raspberry Pi 3 with a clean install of Raspbian, all updated.

Full error on doing npm start in /MagicMirror..

```
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.0.0 start /home/pi/MagicMirror
> electron js/electron.js


npm ERR! Linux 4.4.26-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! magicmirror@2.0.0 start: `electron js/electron.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the magicmirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron js/electron.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs magicmirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls magicmirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/npm-debug.log
pi@raspberrypi:~/MagicMirror $ 
```

**Comment by MichMich** [comment]
Could you give this repo a try to see if electron works at all? https://github.com/electron/electron-quick-start

**Comment by blindarrow** [comment]
Same results it looks like:

```
npm ERR! Linux 4.4.26-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/electron-quick-start/npm-debug.log
pi@raspberrypi:~/electron-quick-start $ 
```

Results from the npm-debug.log:

```
pi@raspberrypi:~/electron-quick-start $ cat /home/pi/electron-quick-start/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/electron-quick-start/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/pi/electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
14 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-quick-start@1.0.0
16 verbose cwd /home/pi/electron-quick-start
17 error Linux 4.4.26-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-quick-start package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-quick-start
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-quick-start
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
pi@raspberrypi:~/electron-quick-start $ 
```

**Comment by Sillec123** [comment]
I have the same error with:
Pi2
electron-v1.4.4

npm ERR! node v6.9.1
npm ERR! npm  v3.10.8


node serveronly is running but PM2 not. 


[STREAMING] Now streaming realtime logs for [all] processes
0|mm       | 2016-10-25T07:16:04.470Z INFO no settings file found, will only use default settings
0|mm       | 2016-10-25T07:16:05.644Z INFO Presets loaded: { example:
0|mm       |    { players:
0|mm       |       [ { roomName: 'Bathroom', volume: 10 },
0|mm       |         { roomName: 'Kitchen', volume: 10 },
0|mm       |         { roomName: 'Office', volume: 10 },
0|mm       |         { roomName: 'Bedroom', volume: 10 },
0|mm       |         { roomName: 'TV Room', volume: 15 } ],
0|mm       |      playMode: { shuffle: true, repeat: 'all', crossfade: false },
0|mm       |      pauseOthers: false,
0|mm       |      favorite: 'My example favorite' } }
0|mm       | 2016-10-25T07:16:05.789Z INFO http server listening on port 5005
/root/.pm2/logs/mm-error-0.log last 10 lines:
0|mm       | npm ERR! Tell the author that this fails on your system:
0|mm       | npm ERR!     electron js/electron.js
0|mm       | npm ERR! You can get information on how to open an issue for this project with:
0|mm       | npm ERR!     npm bugs magicmirror
0|mm       | npm ERR! Or if that isn't available, you can get their info via:
0|mm       | npm ERR!     npm owner ls magicmirror
0|mm       | npm ERR! There is likely additional logging output above.
0|mm       |
0|mm       | npm ERR! Please include the following file with any support request:
0|mm       | npm ERR!     /root/MagicMirror/npm-debug.log

**Comment by MichMich** [comment]
@blindarrow Please open an issue in the electron repository.
@Sillec123 Did you try? https://github.com/electron/electron-quick-start if not, please open an issue in the electron repository.

**Comment by Tajno** [comment]
I've got the same issues, fresh installed OS, cloned your repo - but electonr does not work. Also the quick-start. I've receive the same messages like above.

Think we have to wait for a fix by electron.

**Comment by Sillec123** [comment]
It was a permission problem. Now everything works

**Comment by Tajno** [comment]
Allright, I will have look at this. Do you have a hint which permissions caused the error? Thanks anyway for your feedback.

**Comment by chrisfoerg** [comment]
I also have the same problem on the current jessie lite and raspi 3. 

I am working on a Mac with El Capitan and XQuartz as Xserver. If I am using ssh -X .... it is running without any problems. Maybe this helps.

**Comment by 96Octavian** [comment]
Hi guys, I had this exact issue since this morning: make sure you have libgconf-2-4 and libxss1. I don't know how I figured this out but I installed those two and know in my RPi 2 MagicMirror runs perfectly

**Comment by robozera** [comment]
I get all work with a fresh new Raspbian Jessie install and running all the install since from the beggining in my RPI3 and worked like a charm.

Even though the grunt still warns me about not being installed.

**Comment by casus90** [comment]
Cheers mates.

Today i tryed to install the MM for the first time.
Jessie installation was good. Configuration like you wrote in you manual ([http://michaelteeuw.nl/post/83188136918/magic-mirror-part-v-installing-the-raspberry-pi](url)).
I got to the point where i used the automatic installer `bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"`.
The installation took quite a while and i first thought my pi just froze. After lunch (about one hour later) the installation was kind of done.
Please find attached two screenshots wich i took.
I am an absolute linux/pi rookie. Since this discussion was about "electron is not starting", how do i handle the MM installation, when electron was not even installed?
Can i stop at this point and try the "server only" method? Or is the installation corrupted?

I am using the Raspberry Pi 3 Model B.

![2017-07-13-121023_1200x1920_scrot](https://user-images.githubusercontent.com/15998302/28166426-1b58f2d4-67d8-11e7-9ef2-983a9ea6ee8b.png)
![2017-07-13-121015_1200x1920_scrot](https://user-images.githubusercontent.com/15998302/28166430-1d6547bc-67d8-11e7-9880-b54667c43d91.png)

**Comment by hwikene** [comment]
Hi.
Any updates here? i get the same error as casus90.

**Comment by matteos1** [comment]
raspbery pi3 freeze and mm not work

**Comment by sebcaps** [comment]
@casus90  i got the same issue, but did not had patince to wait node-gyup rebuild... I just edited package.json to 'update' electron version,  In dependencies section (line 57) , update electron version from ^1.6.10"to '^1.7.9'  and sounds good. (no checked everything but install and start is OK)
(I'm using Rpi 3 on Stretch)

Hope it helps

**Comment by wseme** [comment]
I had the same issue on my Raspberry Pi 2 with a fresh install and after upgrading. Nothing above seemed to work.
Electron kept failing to be installed via the bash command/installer.
/usr/lib/node_modules was root.

I tried running: 
```
npm install -g jsonlint
npm install -g electron
```

Both failed for me due to permissions issue.
I ran them both as sudo and this corrected the problem. I doubt this is the best way to do this. But hopefully this willl help get a fix in.

```
sudo npm install -g electron
sudo npm install -g jsonlint
cd ~/MagicMirror/
sh run-start.sh
```

**Comment by E3V3A** [comment]
Using latest Raspbian Stretch with (`4.9.59-v7+`) , this works great out-of-the-box. No problem anywhere. Just make sure to install and update Node, npm and PM2.

**Comment by casus90** [comment]
Cheers,

I am sorry for my late response! I finally found some time to try it again.
This time, I just installed (Automatic Installer) everything from scratch again and it works just fine!
There is nothing else to it. I am sorry :D :D

Best,
Andreas
