### ISSUE TITLE
Config...again!

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#214]
I have changed my config a bit, and now got the msg "warning unknown module 'rrule'" and the mirror doesn't start anymore.
So no problem, switch back the cfg, but still the same problem. 
Used the sample config, same problem. Reset the repo, same problem. 

I would appreciate a service that checks the config on every startup. Any ideas how to achieve this?

**Comment by MichMich** [comment]
Ah, sorry. This is not your config. Will fix this within two hours. In the mean time. Try:

    npm install rrule -g

**Comment by CFenner** [comment]
Ah good to know, by now just my test system is affected, so my wake-up experience with the mm is not compromised ;)

-g is global right, isn't a local instal sufficient?

**Comment by MichMich** [comment]
Could be. Just give it a try.

**Comment by CFenner** [comment]
Thanks, I'll try it tonight.

**Comment by MichMich** [comment]
Will push a fix in 3 minutes ...

**Comment by MichMich** [comment]
Fixed! Don't forget do run `npm install`

**Comment by CFenner** [comment]
still doesn't work. I did a `npm install`, deleted node_module did a install again, nothing changed, rrule is not found :(

**Comment by MichMich** [comment]
Could you try `npm install rrule`

**Comment by CFenner** [comment]
that worked, rrule is not in the dependencies, is this correct?

**Comment by MichMich** [comment]
It is:
https://github.com/MichMich/MagicMirror/blob/v2-beta/package.json#L45

Are you sure you have the latest version?

**Comment by CFenner** [comment]
Oh no! You're right, used the wrong remote...

**Comment by MichMich** [comment]
😁
